spring.datasource.url=jdbc:mysql://localhost:3306/fire_detection_db1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Pavan@2004

# Hibernate ORM config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret Key (Should be in env vars in prod)
jwt.secret=FlareSenseSuperSecretKey123!@#FlareSenseSuperSecretKey123!@#
jwt.expirationMs=86400000

# Server Port
server.port=8080

# --- Resident Email Alert Configuration (Gmail SMTP) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adepuuday51@gmail.com
spring.mail.password=ajfd emct dvnu zvtn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
